version: '3.8'
services:
  sa_node:
    image: node:14-alpine
    volumes:
      - ./:/node
    working_dir: /node
    environment:
      NODE_ENV: test
      STOCK_ALERTS_TABLE_NAME: ddb-t-ew1-stock-alerts
